before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: fkB8Bs/ldy+Tf2cDIKEgW56DGM8UdsFrhztmtkh4yqjUuqqHkZjI7adNw1YcIHmUIX392ep0giUAq17RLoPRjROhwUU3M5K8k/7VSzSXraZ2k/gYVDSWtx6KtVsMBBS6Cji0CIu2mwW2FW6IzMMv+mD6pByFlALKxrhKOppvjnTa5JSIfV0bFprNvJJymXIOXHtirycz1NTKMVy+5KFBeHbUZgD79AvDmgAy2TqeeBqw7VzsYqbFDxxDuiETdh1Wna98vhEjgS5j9DVdX0fg7TB+S7c90GxKBxapnQEDufnpSTt6M7GxNxSWa6EvhC/l1+voP3QN5fqWmZBJywgUxUl/IP+ukE457rs5Ki8OD6/eZCP9Ek1fEIy8M434c0JChKmOTqGw7DIOioN1+pOQPcCOhtChDVhwdzyV9r1mH0C1w6G94owA2NhM3khSI/IHLr/phY/BL6MJlcCNOSk6WGvwEutCLaVPmv8DNN1/HT+w8np/ZWaDUXbN5WNMFSZ5LmNbKEU2JpAEc3WFnW3LnXd2U/ki0V1f+QXs+KPwmLAikJYDe//cQh5PoUsP3AC+J8oolbc7gZ6UzKBCTg4GqoB/Lkstev2d73OQTXcJW/+8upOICCqfBBiaMADpSfXSWkkMWIhirW2hj33W59m+Q8Og6CW3sPHSzuCaqRCth6U= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
